Upgrade phpunit
dannyvankooten/PHP-Router pull request #114
Opened 2017-03-19 00:25 UTC by antoine-pous

- [x] Update to PHPUnit 6
- - [x] RouteTest
- - [x] ConfigTest
- - [x] RouterTest
- - [x] composer.json
- [x] Add PHP 7.1 to travis
- [ ] Validate tests
- - [x] ConfigTest 
- - - Fix missing symfony/yaml dependency)
- - [x] RouteTest
- - - Add test for routes without action
- - [ ] RouterTest

2017-03-19 12:43 UTC, antoine-pous commented
I need your advice on `testParamsWithoutDynamicFilterMatch`. Currently the test fail on 
```PHP
self::assertEquals(
    array(array('filename' => 'someJsFile.min')),
    $router->match('/js/someJsFile.min.js')->getParameters()
);

self::assertEquals(
    array(array('filename' => 'someJsFile.min.js')),
    $router->match('/js/someJsFile.min.js.js')->getParameters()
);
```

This is due to unsupported multiple matches.
`someJsFile` and `someJsFile.min` are matched and we have multiple choices about this behavior:

1. thrown an exception and force developpers to be more strict
1. always return the last match
1. support this kind of behavior

2017-03-20 10:57 UTC, malukenho requested changes

2017-03-20 10:57 UTC, malukenho commented on composer.json
> +    "phpunit/phpunit": "6.*",
use `^`

2017-03-20 10:57 UTC, malukenho commented on src/Route.php
> +                throw new Exception('Invalid filter name `'.$key.'` it should contains only letters, underscore and start with `:`');
We can throw an specific exception here?

2017-03-20 10:57 UTC, malukenho commented on src/Route.php
>          } else {
can we remove the else?

2017-03-20 10:57 UTC, malukenho commented on src/Route.php
> +        if($action === '__construct') {
code style

2017-03-20 10:57 UTC, malukenho commented on src/Route.php
> +            $instance = new $controller($this->parameters);
`class_exists`?

2017-03-20 10:57 UTC, malukenho commented on src/Route.php
> +            call_user_func_array(array($instance, $action), $this->parameters);
shall we use `[]`? Also, Why not drop support to php 5.*?

2017-03-20 10:57 UTC, malukenho commented on src/Route.php
> +        $action = explode('::', $this->config['_controller']);
move `::` to a constant.

2017-03-20 10:57 UTC, malukenho commented on src/Route.php
> +        $this->controller = $action[0];
We probably should abstract or use any other package to instantiate objects for us. Look at the doctrine one.

2017-03-20 10:57 UTC, malukenho commented on src/Route.php
> +        $this->getAction();
ouch!

2017-03-20 10:59 UTC, malukenho commented
As for your question, it should stop on the first assertion and execute controller/method form there.

2017-03-20 11:37 UTC, antoine-pous commented on src/Route.php
> +            call_user_func_array(array($instance, $action), $this->parameters);
See #105

2017-03-20 12:09 UTC, antoine-pous commented on src/Route.php
> +            $instance = new $controller($this->parameters);
Why we should test if the class exists? This is note the job of PHPRouter...

2017-03-20 12:15 UTC, malukenho commented on src/Route.php
> +            $instance = new $controller($this->parameters);
It's not the job of a router instantiate a class and call it a method too... If that's the point just use a service container or some sort.

2017-03-20 12:21 UTC, antoine-pous commented on src/Route.php
> +                throw new Exception('Invalid filter name `'.$key.'` it should contains only letters, underscore and start with `:`');
Wich exception would you throw exactly?

2017-03-20 12:22 UTC, antoine-pous commented on composer.json
> +    "phpunit/phpunit": "6.*",
Fixed

2017-03-20 12:37 UTC, malukenho commented on src/Route.php
> +                throw new Exception('Invalid filter name `'.$key.'` it should contains only letters, underscore and start with `:`');
`InvalidArgumentException` or `RuntimeException` probably.

2017-03-20 16:03 UTC, antoine-pous commented
@malukenho @dannyvankooten i don't understand why `$router->match()` use this:

```php
$currentDir = dirname($_SERVER['SCRIPT_NAME']);
//...
if ('/' !== $currentDir) {
    $requestUrl = str_replace($currentDir, '', $requestUrl);
}
```

When we use filter regex for JS file like `([[:alnum:].]+).js` on route `/js/:filename` the match is broken. This is because `dirname($_SERVER['SCRIPT_NAME']);` return `.`.

I really don't find any usage where this replacement is necessary, can you give me an example please?

2017-03-20 21:44 UTC, antoine-pous commented on src/Route.php
> +        $this->getAction();
Fixed

2017-03-20 21:45 UTC, antoine-pous commented on src/Route.php
> +        $this->controller = $action[0];
I've added ne methods, with them PHPRouter is more flexible

2017-03-22 21:53 UTC, antoine-pous commented
All tests seem OK.

@malukenho Docheader dependency broke the last travis tests, see https://github.com/malukenho/docheader/issues/17 for more informations.

2017-03-23 05:37 UTC, malukenho commented
@antoine-pous As far as I can see your tests is failing due multiples issues.

First, `docheader` doesn't work with php versions bellow `5.5`. So that explains failures for version `5.3` and `5.4`.

Other versions are failing as unit tests is broken, that indicates that bugs were introduced. 
If you're having trouble with `docheader` on your machine. Check if dependencies are installed.

2017-03-23 06:01 UTC, malukenho requested changes

2017-03-23 06:01 UTC, malukenho commented on .travis.yml
>    - 5.6
Can we drop support to 5.6?

2017-03-23 06:01 UTC, malukenho commented on .travis.yml
>    - 7.0
I'd also drop support to `7.0`

2017-03-23 06:01 UTC, malukenho commented on composer.json
> +        "php": "^5.6|^7.0|^7.1",
just `^7.1`

2017-03-23 06:01 UTC, malukenho commented on composer.json
> +        }
Put your name is here.

2017-03-23 06:01 UTC, malukenho commented on composer.json
> +        "phpunit/phpunit": "~5.0",
We can use phpunit `^6.0` 😄

2017-03-23 06:01 UTC, malukenho commented on src/Route.php
> +    private $filtersRegex = ':([a-zA-Z_]+)';
use a constant.

2017-03-23 06:01 UTC, malukenho commented on tests/src/PHPRouterTest/RouterTest.php
> +            array(
`[]`

2017-03-23 06:01 UTC, malukenho commented on tests/src/PHPRouterTest/RouterTest.php
> +            array(
`[]`

2017-03-23 06:01 UTC, malukenho commented on phpunit.xml.dist
> +<phpunit bootstrap="tests/Bootstrap.php"
remove bootstrap, just use `vendor/autoload.php`

2017-03-23 06:01 UTC, malukenho commented on phpunit.xml.dist
> +         backupGlobals="false"
It's `false` by default right?

2017-03-23 06:01 UTC, malukenho commented on phpunit.xml.dist
> +         processIsolation="false"
Isn't it `false` by default?

2017-03-23 06:01 UTC, malukenho commented on phpunit.xml.dist
> +         stopOnFailure="false">
Isn't it `false` by default?

2017-03-23 06:01 UTC, malukenho commented on phpunit.xml.dist
> +            <directory>tests/src/PHPRouterTest/</directory>
leave it as `tests/` only

2017-03-23 06:01 UTC, malukenho commented on phpunit.xml.dist
> +        <log type="junit" target="build/report.junit.xml"/>
`junit`?

2017-03-23 06:01 UTC, malukenho commented on phpunit.xml.dist
> +        <log type="tap" target="build/report.tap"/>
are we using logs for some reason?

2017-03-23 06:01 UTC, malukenho commented on src/Route.php
> +use InvalidArgumentException;
Should be on our own namespace.

2017-03-23 06:01 UTC, malukenho commented on src/Route.php
> +    const ACTION_SEPARATOR = '::';
`Paamayim Nekudotayim`

2017-03-23 06:01 UTC, malukenho commented on src/Route.php
> +     * Controller class
remove this kind of comments that doesn't bring any clarification. instead rename the property to `$controllerClassName` or similar

2017-03-23 06:01 UTC, malukenho commented on src/Route.php
> +    * Method called into the controller class
same as above

2017-03-23 06:01 UTC, malukenho commented on src/Route.php
> +        $this->methods      = isset($config['methods']) ? (array) $config['methods'] : [];
use `??`

2017-03-23 06:01 UTC, malukenho commented on src/Route.php
> +        $this->target       = isset($config['target']) ? $config['target'] : null;
use `??`

2017-03-23 06:01 UTC, malukenho commented on src/Route.php
> +        $this->name         = isset($config['name']) ? $config['name'] : null;
use `??`

2017-03-23 06:01 UTC, malukenho commented on src/Route.php
> +        $this->customParams = isset($config['parameters']) ? (array) $config['parameters'] : [];
use `??`

2017-03-23 06:01 UTC, malukenho commented on src/Route.php
> +        $this->action = !empty($action[1]) && trim($action[1]) !== '' ? $action[1] : '__construct';
what if class doesn't have a `__construct` method defined?
It'll crash badly. 

https://3v4l.org/qTm0F

2017-03-23 06:01 UTC, malukenho commented on src/Route.php
> +    public function setAction($action)
We should avoid setters. please remove them.

2017-03-23 06:01 UTC, malukenho commented on src/Route.php
> +    public function getFiltersRegex()
Nope

2017-03-23 06:01 UTC, malukenho commented on src/Route.php
> +    public function setFiltersRegex($regex)
nope

2017-03-23 06:01 UTC, malukenho commented on src/Router.php
> +            if (!in_array($currentDir, ['.', '/'])) {
missing third parameter

2017-03-23 06:01 UTC, malukenho commented on src/Router.php
> +            $pattern = '@^' . $this->basePath . $route . '/?$@i';
Missing `preg_quote`

2017-03-23 06:01 UTC, malukenho commented on src/Router.php
> +            if (preg_match_all('@' . $routes->getFiltersRegex() . '@', $routes->getUrl(), $argument_keys)) {
the wrapper is very inconsistency across the code

2017-03-23 06:01 UTC, malukenho commented on tests/src/PHPRouterTest/RouteTest.php
> +                'methods' => array(
`[]`

2017-03-23 06:01 UTC, malukenho commented on tests/src/PHPRouterTest/RouteTest.php
> +                '_controller' => 'PHPRouter\Test\SomeController',
`::class`

2017-03-23 06:01 UTC, malukenho commented on tests/src/PHPRouterTest/RouteTest.php
> +        self::assertEquals('__construct', $this->routeWithoutAction->getAction());
nope

2017-03-23 06:01 UTC, malukenho commented on tests/src/PHPRouterTest/RouterTest.php
> +        $route->setFilters(array(':filename' => '([[:alnum:].]+).js'), true);
`[]`

2017-03-23 06:01 UTC, malukenho commented on tests/src/PHPRouterTest/RouterTest.php
>                  '_controller' => 'PHPRouter\Test\SomeController::dynamicFilterUrlMatch',
`::class`

2017-03-23 06:01 UTC, malukenho commented on tests/src/PHPRouterTest/RouterTest.php
> +        $route->setFilters(array(':page_id' => '([a-zA-Z]+)'), true);
`[]`

2017-03-23 06:01 UTC, malukenho commented on tests/src/PHPRouterTest/ConfigTest.php
> +        $this->expectException('InvalidArgumentException');
`::class`

2017-03-23 06:01 UTC, malukenho commented on tests/src/PHPRouterTest/ConfigTest.php
> +class ConfigTest extends TestCase
`final`

2017-03-23 06:01 UTC, malukenho commented on src/Route.php
>      public function setParameters(array $parameters)
can we remove it?

2017-03-23 06:01 UTC, malukenho commented on .travis.yml
> +  - vendor/bin/phpunit -c phpunit.xml.dist
use the call defined on `composer.json`

2017-03-23 06:01 UTC, malukenho commented on .travis.yml
> +  - vendor/bin/docheader check src/ tests/
use the call defined on `composer.json`

2017-03-23 06:01 UTC, malukenho commented on .travis.yml
> +  - vendor/bin/phpcs --standard=psr2 src/
use the call defined on `composer.json`

2017-03-23 06:01 UTC, malukenho commented on .travis.yml
> +  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
use the call defined on `composer.json`

2017-03-23 06:01 UTC, malukenho commented on composer.json
> +    "name": "dannyvankooten/php-router",
Why `retab` this file?

2017-03-23 06:03 UTC, malukenho commented
@antoine-pous if we are bring new things to this code, and refactor this code as you wish, may consider follow `psr-7`  and `psr-11`.

2017-03-23 08:20 UTC, antoine-pous commented on .travis.yml
>    - 5.6
PHP 5.6 is under security support until 31 Dec 2018

2017-03-23 08:21 UTC, antoine-pous commented on .travis.yml
>    - 7.0
PHP 7.0 is under active support until 3 Dec 2017 and security support until 3 Dec 2018

2017-03-23 08:23 UTC, antoine-pous commented on composer.json
> +        "php": "^5.6|^7.0|^7.1",
See previous answers

2017-03-23 08:23 UTC, antoine-pous commented on composer.json
> +        "phpunit/phpunit": "~5.0",
Not currently, due to the support of PHP5.6, but we can creat a branch for each major version of PHP no? :)

2017-03-23 08:25 UTC, antoine-pous commented on src/Route.php
> +    const ACTION_SEPARATOR = '::';
Oh! You're right :confused:

2017-03-23 08:29 UTC, antoine-pous commented on src/Route.php
> +     * Controller class
Fixed

2017-03-23 08:37 UTC, antoine-pous commented on src/Router.php
> +            if (!in_array($currentDir, ['.', '/'])) {
The third parameter is optionnal. Should we really fill in all the optional parameters?

2017-03-23 08:40 UTC, antoine-pous commented on phpunit.xml.dist
> +        <log type="junit" target="build/report.junit.xml"/>
oops my bad, i took phpunit config from my another project wich contain some JAVA :man_facepalming:

2017-03-23 08:46 UTC, antoine-pous commented on phpunit.xml.dist
> +        <log type="tap" target="build/report.tap"/>
Personally i use them. I find the log easier to read and interpret than the terminal.

2017-03-23 08:53 UTC, antoine-pous commented on phpunit.xml.dist
> +<phpunit bootstrap="tests/Bootstrap.php"
The tests crash with this value

2017-03-23 08:53 UTC, antoine-pous commented on phpunit.xml.dist
> +         backupGlobals="false"
PHPUnit author made regulary changes, i want avoid problems due to configuration.

2017-03-23 08:58 UTC, antoine-pous commented on src/Route.php
> +    public function setFiltersRegex($regex)
I think we should let the developper decide wich is the regex used to validate filternames. Sometime it's usefull to use the same syntaxe from another major component of our project.

If it broke the router this is not our problem, we just give a method to set custom filtername validation.

2017-03-23 08:59 UTC, antoine-pous commented on src/Route.php
>      public function setParameters(array $parameters)
Router use it :/

2017-03-23 09:01 UTC, antoine-pous commented on src/Route.php
> +    public function setAction($action)
Why?

2017-03-23 15:44 UTC, malukenho commented on src/Router.php
> +            if (!in_array($currentDir, ['.', '/'])) {
Yep. Be strict at types.

2017-03-23 15:46 UTC, malukenho commented on phpunit.xml.dist
> +        <log type="tap" target="build/report.tap"/>
If it's not part of the `ci` we can remove it. also, you can use a local `phpunit.xml` with your own configs. Just leave what's relevant to the project here.

2017-03-23 15:46 UTC, malukenho commented on phpunit.xml.dist
> +         backupGlobals="false"
Just lock on a specifically version

2017-03-23 15:47 UTC, malukenho commented on phpunit.xml.dist
> +<phpunit bootstrap="tests/Bootstrap.php"
You need to register the namespace using `autoload-dev`

2021-01-03 14:35 UTC, closed without merging